// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using System.Windows.Forms;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// CalculateSalary - Use 'CalculateSalaryParams' to pass parameters into this method.
        /// </summary>
        public void CalculateSalary()
        {
            #region Variable Declarations
            WinEdit uISalaryTextEdit = this.UIForm1Window.UISalaryTextWindow.UISalaryTextEdit;
            WinEdit uIMonthsTextEdit = this.UIForm1Window.UIMonthsTextWindow.UIMonthsTextEdit;
            #endregion

            // The recording for the application under test '\\UON2\Users04\2\psyyf2\SQMCalculator-master\SQMCalculator\bin\Debug\SQMCalculator.exe' may not be correct as it is located on a network share. Please install the application on a local path.

            // Last mouse action was not recorded.

            // Type '10000' in 'salaryText' text box
            //uISalaryTextEdit.Text = this.CalculateSalaryParams.UISalaryTextEditText;

            // Last mouse action was not recorded.

            // Type '12' in 'monthsText' text box
            //uIMonthsTextEdit.Text = this.CalculateSalaryParams.UIMonthsTextEditText;

            // Last mouse action was not recorded.
        }
        
        /// <summary>
        /// TestValue - Use 'TestValueExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestValue(String value)
        {
            #region Variable Declarations
            WinEdit uIBonusTextEdit = this.UIForm1Window.UIBonusTextWindow.UIBonusTextEdit;
            #endregion

            // Verify that the 'ControlType' property of 'bonusText' text box equals '560'
          //  MessageBox.Show(this.TestValueExpectedValues.UIBonusTextEditControlType.ToString());
            Assert.AreEqual(value, uIBonusTextEdit.Text.ToString());
        }
        
        #region Properties
        public virtual CalculateSalaryParams CalculateSalaryParams
        {
            get
            {
                if ((this.mCalculateSalaryParams == null))
                {
                    this.mCalculateSalaryParams = new CalculateSalaryParams();
                }
                return this.mCalculateSalaryParams;
            }
        }
        
        public virtual TestValueExpectedValues TestValueExpectedValues
        {
            get
            {
                if ((this.mTestValueExpectedValues == null))
                {
                    this.mTestValueExpectedValues = new TestValueExpectedValues();
                }
                return this.mTestValueExpectedValues;
            }
        }
        
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        #endregion
        
        #region Fields
        private CalculateSalaryParams mCalculateSalaryParams;
        
        private TestValueExpectedValues mTestValueExpectedValues;
        
        private UIForm1Window mUIForm1Window;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CalculateSalary'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class CalculateSalaryParams
    {
        
        #region Fields
        /// <summary>
        /// Type '10000' in 'salaryText' text box
        /// </summary>
        public string UISalaryTextEditText = "10000";
        
        /// <summary>
        /// Type '12' in 'monthsText' text box
        /// </summary>
        public string UIMonthsTextEditText = "12";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestValue'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class TestValueExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'bonusText' text box equals '560'
        /// </summary>
        public string UIBonusTextEditControlType = "560";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UISalaryTextWindow UISalaryTextWindow
        {
            get
            {
                if ((this.mUISalaryTextWindow == null))
                {
                    this.mUISalaryTextWindow = new UISalaryTextWindow(this);
                }
                return this.mUISalaryTextWindow;
            }
        }
        
        public UIMonthsTextWindow UIMonthsTextWindow
        {
            get
            {
                if ((this.mUIMonthsTextWindow == null))
                {
                    this.mUIMonthsTextWindow = new UIMonthsTextWindow(this);
                }
                return this.mUIMonthsTextWindow;
            }
        }
        
        public UIBonusTextWindow UIBonusTextWindow
        {
            get
            {
                if ((this.mUIBonusTextWindow == null))
                {
                    this.mUIBonusTextWindow = new UIBonusTextWindow(this);
                }
                return this.mUIBonusTextWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISalaryTextWindow mUISalaryTextWindow;
        
        private UIMonthsTextWindow mUIMonthsTextWindow;
        
        private UIBonusTextWindow mUIBonusTextWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISalaryTextWindow : WinWindow
    {
        
        public UISalaryTextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "salaryText";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UISalaryTextEdit
        {
            get
            {
                if ((this.mUISalaryTextEdit == null))
                {
                    this.mUISalaryTextEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUISalaryTextEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Salary Input";
                    this.mUISalaryTextEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUISalaryTextEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUISalaryTextEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMonthsTextWindow : WinWindow
    {
        
        public UIMonthsTextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "monthsText";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIMonthsTextEdit
        {
            get
            {
                if ((this.mUIMonthsTextEdit == null))
                {
                    this.mUIMonthsTextEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIMonthsTextEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Months Input";
                    this.mUIMonthsTextEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIMonthsTextEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIMonthsTextEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBonusTextWindow : WinWindow
    {
        
        public UIBonusTextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "bonusText";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIBonusTextEdit
        {
            get
            {
                if ((this.mUIBonusTextEdit == null))
                {
                    this.mUIBonusTextEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIBonusTextEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIBonusTextEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIBonusTextEdit;
        #endregion
    }
}
